version: "3"
services:
  bd-mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
    - mysql
  playground-web-backend:
    image: playground-web-frontend:latest
    environment:
      PORT: 3000
